name = "pitchey-coming-soon"
main = "worker.js"
compatibility_date = "2024-01-01"
account_id = "002bd5c0e90ae753a387c60546cf6869"

routes = [
  { pattern = "www.pitchey.com/*", zone_name = "pitchey.com" },
  { pattern = "pitchey.com/*", zone_name = "pitchey.com" }
]
